apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-fncm-operator-catalog-subscription
  namespace: REPLACE_NAMESPACE
spec:
  channel: v22.2
  name: ibm-fncm-operator
  installPlanApproval: Automatic
  source: ibm-fncm-operator-catalog
  sourceNamespace: openshift-marketplace
