
apiVersion: fncm.ibm.com/v1
kind: FNCMCluster
metadata:
  name: fncmdeploy
  labels:
    app.kubernetes.io/instance: ibm-fncm
    app.kubernetes.io/managed-by: ibm-fncm
    app.kubernetes.io/name: ibm-fncm
    release: 5.5.10
spec:
  appVersion: 22.0.2
  license:
    accept: true
  content_optional_components:
    cmis: true
    css: true
    es: false
    tm: true

  ecm_configuration:
    fncm_secret_name: ibm-fncm-secret

  shared_configuration:
    sc_deployment_context: FNCM
    show_sensitive_log: true
    image_pull_secrets:
    - ibm-entitlement-key
    sc_image_repository: cp.icr.io
    root_ca_secret: fncm-root-ca
    sc_deployment_patterns: content
    sc_deployment_type: production
    sc_fncm_license_model: "FNCM.PVUNonProd"
    sc_deployment_profile_size: "medium"
    sc_run_as_user:
    sc_deployment_platform: "other"
    trusted_certificate_list: []
    sc_content_initialization: true
    sc_content_verification: false

    storage_configuration:
      sc_slow_file_storage_classname: "efs-sc"
      sc_medium_file_storage_classname: "efs-sc"
      sc_fast_file_storage_classname: "efs-sc"

  ldap_configuration:
    lc_selected_ldap_type: "Custom"
    lc_ldap_precheck: true
    lc_ldap_server: "10.100.217.46"
    lc_ldap_port: "389"
    lc_bind_secret: ldap-bind-secret
    lc_ldap_base_dn: "dc=filenet,dc=internal"
    lc_ldap_ssl_enabled: false
    lc_ldap_ssl_secret_name: "ldap"
    lc_ldap_user_name_attribute: "*:uid"
    lc_ldap_user_display_name_attr: "cn"
    lc_ldap_group_base_dn: "ou=Groups,dc=filenet,dc=internal"
    lc_ldap_group_name_attribute: "*:cn"
    lc_ldap_group_display_name_attr: "cn"
    lc_ldap_group_membership_search_filter: "(|(&(objectclass='groupOfNames')(member={0}))(&(objectclass=groupofuniquenames)(uniquemember={0})))')"
    lc_ldap_group_member_id_map: "groupofnames:member"
    custom:
      lc_user_filter: "(&(uid=%v)(objectclass=inetOrgPerson))"
      lc_group_filter: "(&(cn=%v)(|(objectclass=groupOfNames)(objectclass=groupofuniquenames)(objectclass=groupofurls)))"

  datasource_configuration:
    dc_ssl_enabled: false
    database_precheck: false
    dc_gcd_datasource:
      dc_database_type: "postgresql"
      dc_common_gcd_datasource_name: "FNGCDDS"
      dc_common_gcd_xa_datasource_name: "FNGCDDSXA"
      database_servername: "10.100.80.28"
      database_name: "gcddb"
      database_port: "5432"
    dc_os_datasources:
    - dc_database_type: "postgresql"
      dc_os_label: "os"
      dc_common_os_datasource_name: "FNOS1DS"
      dc_common_os_xa_datasource_name: "FNOS1DSXA"
      database_servername: "10.100.80.28"
      database_name: "osdb"
      database_port: "5432"
    dc_icn_datasource:
      dc_database_type: "postgresql"
      dc_common_icn_datasource_name: "ECMClientDS"
      database_servername: "10.100.80.28"
      database_port: "5432"
      database_name: "icndb"
#  ########################################################################
#  ######## IBM FileNet Content Manager Initialization configuration ######
#  ########################################################################
#  ## This section is required when initializing the P8 domain and object store
#  ## Please fill out the "<Required>" parameters
#  initialize_configuration:
#    ic_ldap_creation:
#      ic_ldap_admin_user_name:
#        - "<Required>" # user name for P8 domain admin, for example, "CEAdmin".  This parameter accepts a list of values.
#      ic_ldap_admins_groups_name:
#        - "<Required>" # group name for P8 domain admin, for example, "P8Administrators".  This parameter accepts a list of values.
#    ic_obj_store_creation:
#      object_stores:
#        - oc_cpe_obj_store_display_name: "OS01" # Required display name of the object store, for example, "OS01"
#          oc_cpe_obj_store_symb_name: "OS01" # Required symbolic name of the object store, for example, "OS01"
#          oc_cpe_obj_store_conn:
#            name: "OS01_dbconnection"
#            dc_os_datasource_name: "FNOS1DS" # This value must match with the non-XA datasource name in the "datasource_configuration" above.
#            dc_os_xa_datasource_name: "FNOS1DSXA" # This value must match with the XA datasource name in the "datasource_configuration" above.
#          oc_cpe_obj_store_admin_user_groups:
#            - "<Required>" # user name and group name for object store admin, for example, "CEAdmin" or "P8Administrators".  This parameter accepts a list of values.
#
#  ########################################################################
#  ######## IBM FileNet Content Manager Verification configuration ######
#  ########################################################################
#  ## After the initialization process (see section above), the verification process will take place.
#  ## The verification process ensures that the FNCM and BAN components are functioning correctly.  The verification
#  ## process includes creation of a CPE folder, a CPE document, a CBR search, verifying the workflow configuration,
#  ## and validation of the ICN desktop.
#  verify_configuration:
#    vc_cpe_verification:
#      vc_cpe_folder:
#        - folder_cpe_obj_store_name: "OS01"
#          folder_cpe_folder_path: "/TESTFOLDER"
#      vc_cpe_document:
#        - doc_cpe_obj_store_name: "OS01"
#          doc_cpe_folder_name: "/TESTFOLDER"
#          doc_cpe_doc_title: "test_title"
#          DOC_CPE_class_name: "Document"
#          doc_cpe_doc_content: "This is a simple document test"
#          doc_cpe_doc_content_name: "doc_content_name"
#      vc_cpe_cbr:
#        - cbr_cpe_obj_store_name: "OS01"
#          cbr_cpe_class_name: "Document"
#          cbr_cpe_search_string: "is a simple"
#      vc_cpe_workflow:
#        - workflow_cpe_enabled: false
#          workflow_cpe_connection_point: "pe_conn_os1"
#    vc_icn_verification:
#      - vc_icn_repository: "OS01repo"
#        vc_icn_desktop_id: "desktop1"
